In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [11]:
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoder, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [12]:
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [13]:
X=data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary']

In [14]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.25, random_state=40)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [15]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791615120.775066  557010 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1791615120.783408  557010 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1791615121.771049  557010 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791615126.842730  557010 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1791615126.847189  557010 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [18]:
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

In [21]:
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
log_dir='regressionlogs/fit'+datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
#log_dir='/content/drive/MyDrive/logs/fit/'+datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [23]:
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [24]:
history=model.fit(
    X_train, y_train, validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorflow_callback]
)

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 100192.0547 - mae: 100192.0547 - val_loss: 99490.9688 - val_mae: 99490.9688
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 99592.9609 - mae: 99592.9609 - val_loss: 98261.3672 - val_mae: 98261.3672
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 97458.0312 - mae: 97458.0312 - val_loss: 95061.3984 - val_mae: 95061.3984
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 93148.3359 - mae: 93148.3359 - val_loss: 89554.2031 - val_mae: 89554.2031
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 86617.1172 - mae: 86617.1172 - val_loss: 82132.7656 - val_mae: 82132.7656
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 78606.4688 - mae: 78606.4688 - val_loss: 73847.5547 - val_mae: 73847.5547
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 70205.5859 - mae: 70205.5859 - val_loss: 66089.5078 - val_mae: 66089.5078
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 62659.5508 - mae: 62659.5508 - val_loss: 59709.8438 - val_mae: 59709.8438
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 56964.6406 - mae: 56964.6406 - val_loss: 55500.6211 - val_mae: 55500.6211
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 53390.5273 - mae: 53390.5273 - val_loss: 53250.7539 - val_mae: 53250.7539
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 51494.8477 - mae: 51494.8477 - val_loss: 52109.2031 - val_mae: 52109.2031
Epoch 12/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50678.1133 - mae: 50678.1133 - val_loss: 51659.7812 - val_mae: 51659.7812
Epoch 13/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50361.6367 - mae: 50361.6367 - val_loss: 51465.0469 - val_mae: 51465.0469
Epoch 14/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50207.4375 - mae: 50207.4375 - val_loss: 51348.1445 - val_mae: 51348.1445
Epoch 15/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50111.3555 - mae: 50111.3555 - val_loss: 51281.3477 - val_mae: 51281.3477
Epoch 16/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50036.2070 - mae: 50036.2070 - val_loss: 51228.1094 - val_mae: 51228.1094
Epoch 17/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49975.7266 - mae: 49975.7266 - val_loss: 51189.3867 - val_mae: 51189.3867
Epoch 18/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49923.9805 - mae: 49923.9805 - val_loss: 51155.8672 - val_mae: 51155.8672
Epoch 19/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49877.3203 - mae: 49877.3203 - val_loss: 51121.9336 - val_mae: 51121.9336
Epoch 20/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49840.0898 - mae: 49840.0898 - val_loss: 51096.4336 - val_mae: 51096.4336
Epoch 21/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49801.6094 - mae: 49801.6094 - val_loss: 51067.2734 - val_mae: 51067.2734
Epoch 22/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49772.1523 - mae: 49772.1523 - val_loss: 51039.7383 - val_mae: 51039.7383
Epoch 23/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49744.4102 - mae: 49744.4102 - val_loss: 51020.8438 - val_mae: 51020.8438
Epoch 24/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49718.4727 - mae: 49718.4727 - val_loss: 50995.2617 - val_mae: 50995.2617
Epoch 25/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49695.5234 - mae: 49695.5234 - val_loss: 50973.0391 - val_mae: 50973.0391
Epoch 26/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49672.3242 - mae: 49672.3242 - val_loss: 50950.8945 - val_mae: 50950.8945
Epoch 27/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49649.8594 - mae: 49649.8594 - val_loss: 50933.9141 - val_mae: 50933.9141
Epoch 28/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49630.3047 - mae: 49630.3047 - val_loss: 50915.6914 - val_mae: 50915.6914
Epoch 29/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49612.8359 - mae: 49612.8359 - val_loss: 50899.5781 - val_mae: 50899.5781
Epoch 30/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49599.8867 - mae: 49599.8867 - val_loss: 50882.3477 - val_mae: 50882.3477
Epoch 31/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49584.3750 - mae: 49584.3750 - val_loss: 50866.0938 - val_mae: 50866.0938
Epoch 32/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49568.3125 - mae: 49568.3125 - val_loss: 50849.4531 - val_mae: 50849.4531
Epoch 33/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49551.5859 - mae: 49551.5859 - val_loss: 50832.6172 - val_mae: 50832.6172
Epoch 34/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49541.7734 - mae: 49541.7734 - val_loss: 50821.3281 - val_mae: 50821.3281
Epoch 35/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49525.0859 - mae: 49525.0859 - val_loss: 50801.0938 - val_mae: 50801.0938
Epoch 36/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49515.9336 - mae: 49515.9336 - val_loss: 50787.3438 - val_mae: 50787.3438
Epoch 37/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49501.3008 - mae: 49501.3008 - val_loss: 50774.1641 - val_mae: 50774.1641
Epoch 38/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49490.6875 - mae: 49490.6875 - val_loss: 50768.4727 - val_mae: 50768.4727
Epoch 39/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49479.4453 - mae: 49479.4453 - val_loss: 50754.7461 - val_mae: 50754.7461
Epoch 40/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49471.4375 - mae: 49471.4375 - val_loss: 50750.3633 - val_mae: 50750.3633
Epoch 41/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49461.3477 - mae: 49461.3477 - val_loss: 50743.8242 - val_mae: 50743.8242
Epoch 42/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49450.4688 - mae: 49450.4688 - val_loss: 50727.2617 - val_mae: 50727.2617
Epoch 43/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49442.1406 - mae: 49442.1406 - val_loss: 50716.9297 - val_mae: 50716.9297
Epoch 44/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49434.2578 - mae: 49434.2578 - val_loss: 50712.0469 - val_mae: 50712.0469
Epoch 45/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49427.7617 - mae: 49427.7617 - val_loss: 50703.0156 - val_mae: 50703.0156
Epoch 46/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49418.9180 - mae: 49418.9180 - val_loss: 50697.2109 - val_mae: 50697.2109
Epoch 47/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49410.4844 - mae: 49410.4844 - val_loss: 50690.3281 - val_mae: 50690.3281
Epoch 48/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49403.0156 - mae: 49403.0156 - val_loss: 50690.6641 - val_mae: 50690.6641
Epoch 49/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49398.8086 - mae: 49398.8086 - val_loss: 50676.2227 - val_mae: 50676.2227
Epoch 50/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49390.2344 - mae: 49390.2344 - val_loss: 50674.4297 - val_mae: 50674.4297
Epoch 51/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49385.9492 - mae: 49385.9492 - val_loss: 50666.5469 - val_mae: 50666.5469
Epoch 52/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49376.3438 - mae: 49376.3438 - val_loss: 50664.1836 - val_mae: 50664.1836
Epoch 53/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49371.9414 - mae: 49371.9414 - val_loss: 50659.7227 - val_mae: 50659.7227
Epoch 54/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49367.2891 - mae: 49367.2891 - val_loss: 50656.9297 - val_mae: 50656.9297
Epoch 55/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49357.7461 - mae: 49357.7461 - val_loss: 50651.3008 - val_mae: 50651.3008
Epoch 56/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49351.5859 - mae: 49351.5859 - val_loss: 50646.8047 - val_mae: 50646.8047
Epoch 57/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49347.1602 - mae: 49347.1602 - val_loss: 50641.5352 - val_mae: 50641.5352
Epoch 58/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49342.5742 - mae: 49342.5742 - val_loss: 50631.8125 - val_mae: 50631.8125
Epoch 59/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49333.8398 - mae: 49333.8398 - val_loss: 50628.1875 - val_mae: 50628.1875
Epoch 60/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49330.6875 - mae: 49330.6875 - val_loss: 50623.2930 - val_mae: 50623.2930
Epoch 61/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49326.9062 - mae: 49326.9062 - val_loss: 50619.5312 - val_mae: 50619.5312
Epoch 62/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49320.3633 - mae: 49320.3633 - val_loss: 50609.6914 - val_mae: 50609.6914
Epoch 63/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49318.6094 - mae: 49318.6094 - val_loss: 50611.7734 - val_mae: 50611.7734
Epoch 64/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49314.8633 - mae: 49314.8633 - val_loss: 50609.0977 - val_mae: 50609.0977
Epoch 65/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49308.9219 - mae: 49308.9219 - val_loss: 50604.6523 - val_mae: 50604.6523
Epoch 66/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49302.0234 - mae: 49302.0234 - val_loss: 50606.0039 - val_mae: 50606.0039
Epoch 67/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49300.7188 - mae: 49300.7188 - val_loss: 50603.2305 - val_mae: 50603.2305
Epoch 68/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49294.5352 - mae: 49294.5352 - val_loss: 50594.8672 - val_mae: 50594.8672
Epoch 69/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49289.7891 - mae: 49289.7891 - val_loss: 50588.9570 - val_mae: 50588.9570
Epoch 70/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49285.8164 - mae: 49285.8164 - val_loss: 50586.7695 - val_mae: 50586.7695
Epoch 71/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49284.7109 - mae: 49284.7109 - val_loss: 50584.1875 - val_mae: 50584.1875
Epoch 72/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49281.1055 - mae: 49281.1055 - val_loss: 50578.8086 - val_mae: 50578.8086
Epoch 73/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49277.3242 - mae: 49277.3242 - val_loss: 50578.7852 - val_mae: 50578.7852
Epoch 74/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49273.9414 - mae: 49273.9414 - val_loss: 50572.5820 - val_mae: 50572.5820
Epoch 75/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49267.6641 - mae: 49267.6641 - val_loss: 50566.9297 - val_mae: 50566.9297
Epoch 76/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49265.6133 - mae: 49265.6133 - val_loss: 50564.5234 - val_mae: 50564.5234
Epoch 77/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49263.0078 - mae: 49263.0078 - val_loss: 50564.9961 - val_mae: 50564.9961
Epoch 78/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49260.9570 - mae: 49260.9570 - val_loss: 50564.8242 - val_mae: 50564.8242
Epoch 79/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49254.4805 - mae: 49254.4805 - val_loss: 50561.7500 - val_mae: 50561.7500
Epoch 80/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49255.1836 - mae: 49255.1836 - val_loss: 50553.4805 - val_mae: 50553.4805
Epoch 81/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49251.0820 - mae: 49251.0820 - val_loss: 50554.0000 - val_mae: 50554.0000
Epoch 82/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49246.5586 - mae: 49246.5586 - val_loss: 50552.3008 - val_mae: 50552.3008
Epoch 83/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49243.2461 - mae: 49243.2461 - val_loss: 50550.1445 - val_mae: 50550.1445
Epoch 84/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49241.1875 - mae: 49241.1875 - val_loss: 50542.8789 - val_mae: 50542.8789
Epoch 85/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49236.3438 - mae: 49236.3438 - val_loss: 50542.0977 - val_mae: 50542.0977
Epoch 86/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49233.0898 - mae: 49233.0898 - val_loss: 50539.4609 - val_mae: 50539.4609
Epoch 87/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49233.4609 - mae: 49233.4609 - val_loss: 50539.1289 - val_mae: 50539.1289
Epoch 88/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49226.9727 - mae: 49226.9727 - val_loss: 50538.6641 - val_mae: 50538.6641
Epoch 89/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49226.9414 - mae: 49226.9414 - val_loss: 50533.9141 - val_mae: 50533.9141
Epoch 90/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49222.7969 - mae: 49222.7969 - val_loss: 50533.9805 - val_mae: 50533.9805
Epoch 91/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49218.9258 - mae: 49218.9258 - val_loss: 50533.7344 - val_mae: 50533.7344
Epoch 92/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49216.1914 - mae: 49216.1914 - val_loss: 50532.8984 - val_mae: 50532.8984
Epoch 93/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49215.9922 - mae: 49215.9922 - val_loss: 50529.1289 - val_mae: 50529.1289
Epoch 94/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49214.4297 - mae: 49214.4297 - val_loss: 50531.4062 - val_mae: 50531.4062
Epoch 95/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 49210.9531 - mae: 49210.9531 - val_loss: 50528.7305 - val_mae: 50528.7305
Epoch 96/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49209.3906 - mae: 49209.3906 - val_loss: 50525.8164 - val_mae: 50525.8164
Epoch 97/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49203.9297 - mae: 49203.9297 - val_loss: 50524.4492 - val_mae: 50524.4492
Epoch 98/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49204.0625 - mae: 49204.0625 - val_loss: 50522.4570 - val_mae: 50522.4570
Epoch 99/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49199.8242 - mae: 49199.8242 - val_loss: 50520.4141 - val_mae: 50520.4141
Epoch 100/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49197.7930 - mae: 49197.7930 - val_loss: 50521.4414 - val_mae: 50521.4414

In [25]:
%load_ext tensorboard

In [29]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 614345), started 0:01:27 ago. (Use '!kill 614345' to kill it.)

In [31]:
test_loss, test_mae=model.evaluate(X_test, y_test)
print('Test MAE:',test_mae)

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50520.4141 - mae: 50520.4141
Test MAE: 50520.4140625

In [32]:
model.save('regresstion_model.keras')